@QuizAPIELECT2_HostAddress = http://localhost:5070

### LOGIN 
POST {{QuizAPIELECT2_HostAddress}}/api/auth/login
Content-Type: application/json
X-API-KEY: matteo123

{
  "username": "admin",
  "password": "12345678"
}


---

###  GET ALL TASKS 
GET {{QuizAPIELECT2_HostAddress}}/api/tasks
Authorization: Bearer {{token}} 

---

### GET TASK 
GET {{QuizAPIELECT2_HostAddress}}/api/tasks/1
Authorization: Bearer {{token}} YOUR_TOKEN_HERE

---

### CREATE TASK 
POST {{QuizAPIELECT2_HostAddress}}/api/tasks
Authorization: Bearer {{token}} YOUR_TOKEN_HERE
Content-Type: application/json

{
  "title": "Web API Task",
  "isCompleted": false
}

---

###  UPDATE TASK 
PUT {{QuizAPIELECT2_HostAddress}}/api/tasks/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Updated Task",
  "isCompleted": true
}

---

###  DELETE TASK 
DELETE {{QuizAPIELECT2_HostAddress}}/api/tasks/1
Authorization: Bearer {{token}}