@Web_API_Quiz_HostAddress = https://localhost:7249
@apiKey = WebAPIKey-1


@adminToken = YOUR_ADMIN_JWT_TOKEN_HERE
@userToken = YOUR_USER_JWT_TOKEN_HERE



### LOGIN ADMIN
POST {{Web_API_Quiz_HostAddress}}/api/auth/login
Content-Type: application/json
X-API-KEY: {{apiKey}}

{
  "username": "admin",
  "password": "admin123"
}



### LOGIN 
POST {{Web_API_Quiz_HostAddress}}/api/auth/login
Content-Type: application/json
X-API-KEY: {{apiKey}}

{
  "username": "user1",
  "password": "user123"
}





### GET ALL TASKS ADMIN & USER
GET {{Web_API_Quiz_HostAddress}}/api/tasks
Authorization: Bearer {{userToken}}



### GET TASK IN ID
GET {{Web_API_Quiz_HostAddress}}/api/tasks/1
Authorization: Bearer {{userToken}}



### CREATE TASK ADMIN & USER
POST {{Web_API_Quiz_HostAddress}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Sample Task 3",
  "isCompleted": false
}



### UPDATE TASK ADMIN 
PUT {{Web_API_Quiz_HostAddress}}/api/tasks/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "Task 2",
  "isCompleted": false
}


### DELETE TASK ADMIN 
DELETE {{Web_API_Quiz_HostAddress}}/api/tasks/1
Authorization: Bearer {{adminToken}}